import 'package:book_shelf/config/image_strings.dart';
import 'package:book_shelf/model/book_model.dart';

var bookData = [
  BookModel(
    id: "1",
    title: "Learn to Program With C",
    description:
        "Start Your computer Science Journey with C Programming. Get Your Goal",
    aboutAuthor: "Tim David by computer Programmer",
    audioLen: "20h🕥",
    audioUrl: "",
    author: "Tim David",
    bookUrl: "",
    category: "Documentary",
    coverUrl: "assets/images/c_programming_book.jpg",
    language: "ENG",
    numberOfRating: "2345",
    pages: 450,
    price: 238,
    rating: "4.5",
  ),
  BookModel(
    id: "2",
    title: "Learn to Program With cnc",
    description:
        "Start Your computer Science Journey with C Programming. Get Your Goal",
    aboutAuthor: "Tim David by computer Programmer",
    audioLen: "20h🕥",
    audioUrl: "",
    author: "Tim David",
    bookUrl: "",
    category: "Documentary",
    coverUrl: AppImageStrings.cncProgramming,
    language: "ENG",
    numberOfRating: "2345",
    pages: 450,
    price: 238,
    rating: "4.5",
  ),
  BookModel(
    id: "3",
    title: "Learn to Program With python",
    description:
        "Start Your computer Science Journey with C Programming. Get Your Goal",
    aboutAuthor: "Tim David by computer Programmer",
    audioLen: "20h🕥",
    audioUrl: "",
    author: "Tim David",
    bookUrl: "",
    category: "Documentary",
    coverUrl: AppImageStrings.pythonProgramming,
    language: "ENG",
    numberOfRating: "2345",
    pages: 450,
    price: 238,
    rating: "4.5",
  ),
  BookModel(
    id: "4",
    title: "Learn to Program With Java",
    description:
        "Start Your computer Science Journey with C Programming. Get Your Goal",
    aboutAuthor: "Tim David by computer Programmer",
    audioLen: "20h🕥",
    audioUrl: "",
    author: "Tim David",
    bookUrl: "",
    category: "Documentary",
    coverUrl: AppImageStrings.javaProgramming,
    language: "ENG",
    numberOfRating: "2345",
    pages: 450,
    price: 238,
    rating: "4.5",
  ),
  BookModel(
    id: "5",
    title: "Learn to Program With JavaScript",
    description:
        "Start Your computer Science Journey with C Programming. Get Your Goal",
    aboutAuthor: "Tim David by computer Programmer",
    audioLen: "20h🕥",
    audioUrl: "",
    author: "Tim David",
    bookUrl: "",
    category: "Documentary",
    coverUrl: AppImageStrings.javaScrpitProgramming,
    language: "ENG",
    numberOfRating: "2345",
    pages: 450,
    price: 238,
    rating: "4.5",
  ),
  BookModel(
    id: "5",
    title: "Learn to Program With linux",
    description:
        "Start Your computer Science Journey with C Programming. Get Your Goal",
    aboutAuthor: "Tim David by computer Programmer",
    audioLen: "20h🕥",
    audioUrl: "",
    author: "Tim David",
    bookUrl: "",
    category: "Documentary",
    coverUrl: AppImageStrings.linuxProgramming,
    language: "ENG",
    numberOfRating: "2345",
    pages: 450,
    price: 238,
    rating: "4.5",
  ),
];
